# Generated by Django 2.1.3 on 2018-11-19 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('picture', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres_category', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('duration', models.CharField(max_length=250)),
                ('ratings', models.IntegerField()),
                ('language', models.CharField(max_length=250)),
                ('poster', models.CharField(max_length=1000)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Director')),
                ('genres', models.ManyToManyField(to='movie.Genres')),
            ],
        ),
    ]
