# Generated by Django 2.1.2 on 2018-11-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
