# Generated by Django 2.1.2 on 2018-11-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movies_is_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='genres',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
